version: '3'

services:
  lotuscms-backend:
    build: ./backend
    volumes:
      - ./backend:/usr/src/app
      - /app/node_modules
    ports:
      - 4000:4000
    command: yarn start-prod
  lotuscms-frontend:
    build: ./frontend
    volumes:
      - ./frontend:/usr/src/app
      - /app/node_modules
    ports:
      - 8080:8080
    command: yarn start-prod